apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-log-output
      containers:
        - name: log-outputter
          image: jhirvioja/log-outputter:0.0.1
          volumeMounts:
            - name: shared-log-output
              mountPath: /usr/src/app/files
        - name: log-generator
          image: jhirvioja/log-generator:0.0.1
          volumeMounts:
            - name: shared-log-output
              mountPath: /usr/src/app/files
