apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: ping-pong
          image: jhirvioja/ping-pong:0.0.9
          env:
            - name: "DATABASE_URL"
              value: "postgres://admin:adminpassword@psql-svc:5432/logoutput?sslmode=disable"
