apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      securityContext:
        fsGroup: 1000
      # volumes:
      #   - name: shared-log-output
      #     persistentVolumeClaim:
      #       claimName: dwk-pv-claim
      containers:
        - name: ping-pong
          image: jhirvioja/ping-pong:0.0.7
          # volumeMounts:
          #   - name: shared-log-output
          #     mountPath: /usr/src/app/files
