apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: ping-pong
          image: jhirvioja/ping-pong:0.0.10
          resources:
            limits:
              cpu: "100m"
              memory: "86Mi"
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-username
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-database
                  key: DB_DATABASE
