apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/cronjob.yaml
  - manifests/deployment.yaml
  - manifests/ingress.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/secrets.yaml
  - manifests/services.yaml
  - manifests/statefulset.yaml
images:
  - name: PROJECT/FE-IMAGE
    newName: jhirvioja/project-todo-frontend:0.0.8
  - name: PROJECT/BE-IMAGE
    newName: jhirvioja/project-todo-backend:0.0.7
