apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-reminder
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: project-cronjob
              image: jhirvioja/project-reminder:0.0.2
              env:
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: todo-secrets
                      key: DB_USERNAME
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: todo-secrets
                      key: DB_PASSWORD
                - name: DB_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: todo-secrets
                      key: DB_DATABASE
          restartPolicy: OnFailure
