apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: shared-log-output
          persistentVolumeClaim:
            claimName: dwk-pv-claim
      containers:
        - name: project
          image: jhirvioja/project:0.0.6
          volumeMounts:
            - name: shared-log-output
              mountPath: /usr/src/app/files
