apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
  namespace: todo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: shared-log-output
          persistentVolumeClaim:
            claimName: dwk-pv-claim
      containers:
        - name: project
          image: PROJECT/FE-IMAGE
          volumeMounts:
            - name: shared-log-output
              mountPath: /usr/src/app/files
        - name: project-todo-backend
          image: PROJECT/BE-IMAGE
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-username
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-database
                  key: DB_DATABASE
