apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-ingress-v2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: project-frontend-svc
                port:
                  number: 80
          - path: /todos
            pathType: Prefix
            backend:
              service:
                name: project-svc
                port:
                  number: 5678
