name: Delete Kubernetes Environment

on:
  delete:
    branches:
      - "**"

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-c
  SERVICE: project
  NAMESPACE: ${{ github.ref_name }}

jobs:
  delete-environment:
    name: Delete Kubernetes Environment
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Get credentials from secrets"
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "Use gcloud CLI"
        run: gcloud info

      - name: "Get GKE credentials"
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ env.GKE_ZONE }}"

      - name: Delete Kubernetes Namespace
        if: ${{ github.ref_name != 'main' }}
        run: |-
          kubectl delete namespace $NAMESPACE || true
